# Generated by Django 5.0.3 on 2024-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genome_id', models.CharField(max_length=50)),
                ('clade', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('length', models.IntegerField()),
                ('sequence', models.TextField(max_length=500000)),
            ],
        ),
    ]
