# Generated by Django 5.0.3 on 2024-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=200)),
            ],
        ),
    ]
